analytics:
  outputs:
    docker:
      dbname: "{{ env_var('DB_NAME') }}"
      user: "{{ env_var('DB_USER') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      port: 5432
      threads: 1
      type: postgres
    local:
      dbname: postgres
      user: postgres
      host: localhost # host.docker.internal
      pass: postgres
      schema: analytics
      port: 5432
      threads: 1
      type: postgres
  target: docker
