analytics:
  outputs:
    docker:
      dbname: postgres
      host: host.docker.internal
      pass: postgres
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: postgres
    local:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: postgres
  target: docker
  