version: 2

sources:
  - name: game
    schema: game
    tables:
      - name: schedule
      - name: result
  - name: player
    schema: player
    tables:
      - name: hitter_season_summary
      - name: pitcher_season_summary
      - name: fielder_season_summary
      - name: runner_season_summary
