analytics_dbt:
  outputs:
    dev:
      dataset: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../config/key.json
      location: US
      method: service-account
      priority: interactive
      project: kbo-data-project
      threads: 1
      type: bigquery
  target: dev
