with pitcher_stats as (
    select 
        "SEASON_ID", 
        "TEAM_NM",
        sum("G") as "G",
        sum("W") as "W",
        sum("L") as "L",
        sum("SV") as "SV",
        sum("HLD") as "HLD",
        sum("WPCT") as "WPCT",
        sum("IP") as "IP",
        sum("H") as "H",
        sum("HR") as "HR",
        sum("BB") as "BB",
        sum("HBP") as "HBP",
        sum("SO") as "SO",
        sum("R") as "R",
        sum("ER") as "ER",
        sum("WHIP") as "WHIP",
        sum("CG") as "CG",
        sum("SHO") as "SHO",
        sum("QS") as "QS",
        sum("BSV") as "BSV",
        sum("TBF") as "TBF",
        sum("NP") as "NP",
        sum("AVG") as "AVG",
        sum("2B") as "2B",
        sum("3B") as "3B",
        sum("SAC") as "SAC",
        sum("SF") as "SF",
        sum("IBB") as "IBB",
        sum("WP") as "WP",
        sum("BK") as "BK",
        sum("GS") as "GS",
        sum("WGS") as "WGS",
        sum("WGR") as "WGR",
        sum("GF") as "GF",
        sum("SVO") as "SVO",
        sum("TS") as "TS",
        sum("GDP") as "GDP",
        sum("GO") as "GO",
        sum("AO") as "AO",
        sum("GO_AO") as "GO_AO",
        sum("BABIP") as "BABIP",
        sum("P_G") as "P_G",
        sum("P_IP") as "P_IP",
        sum("K_9") as "K_9",
        sum("BB_9") as "BB_9",
        sum("K_BB") as "K_BB",
        sum("OBP") as "OBP",
        sum("SLG") as "SLG",
        sum("OPS") as "OPS"
    from {{ source('public', 'player_pitcher_stats') }}
    group by "SEASON_ID", "TEAM_NM"
	order by "SEASON_ID", "TEAM_NM"
)

select * from pitcher_stats